.TH CLISCREEN_CREATE 3 2021-12-23 "libcliscreen 0.?.?" "Manual for libcliscreen"
.SH NAME
cliscreen_create, cliscreen_destroy - create/destroy the screen
.SH SYNOPSIS
.nf
.B #include \fB"\fPvulcalien/cliscreen.h\fB"\fP
.PP
.BI "int  cliscreen_create(void);"
.BI "void cliscreen_destroy(void);"
.fi
.SH DESCRIPTION
The
.BR cliscreen_create ()
function initializes the screen. The raster remains inoperable until
.BR cliscreen_setsize (3)
is called.
.PP
The
.BR cliscreen_destroy ()
function destroys the screen, freeing any allocated memory.
.SH RETURN VALUE
The
.BR cliscreen_create ()
function returns 0 on success or nonzero on failure.
.PP
The
.BR cliscreen_destroy ()
function returns no value.
.SH SEE ALSO
.BR cliscreen_setsize (3),
.BR cliscreen_terminal_prepare (3),
.BR cliscreen_terminal_reset (3)
