.TH CLISCREEN_SETSIZE 3 2021-12-23 "libcliscreen 0.?.?" "Manual for libcliscreen"
.SH NAME
cliscreen_setsize - set the screen's size
.SH SYNOPSIS
.nf
.B #include \fB"\fPvulcalien/cliscreen.h\fB"\fP
.PP
.BI "void cliscreen_setsize(u32 w, u32 h);"
.fi
.SH DESCRIPTION
The
.BR cliscreen_setsize ()
function sets the size of the screen.
.SH RETURN VALUE
No value is returned.
.SH SEE ALSO
.BR cliscreen_create (3),
.BR cliscreen_setalign (3)
